In [1]:
import numpy as np
print(np.__version__)

1.23.5


In [2]:
a1  =[[1.2],[3,4],[5,6]]
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)

2


In [3]:
print(a.shape)

(3, 2)


In [4]:
b=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(b.shape)

(2, 3, 2)


In [5]:
print(b.ndim)

3


In [6]:
c = np.array([43])
print(c.ndim)

1


In [7]:
d = np.array([1,2,3,4])
print(d.ndim)

1


In [8]:
e = np.array([1,2,3,4],ndmin = 2)
print(e)

[[1 2 3 4]]


In [9]:
arr = np.array([10,20,30,40,50,60])
print(arr[1])

20


In [10]:
print(arr[2:])
print(arr[:3])
#line itrited 2 by 2
print(arr[0::2])

[30 40 50 60]
[10 20 30]
[10 30 50]


In [11]:
arr1 =  np.array([[1,2],[3,4]])
print(arr1[1,0])

3


In [12]:
arr = np.array([1.5,3.5,2.6])
print(arr.dtype)

float64


In [13]:
arr1 = arr.astype('i')
print(arr1)
print(arr1.dtype)

[1 3 2]
int32


In [17]:
arr = np.array([1,3,2,4,5])
arr1 = arr.astype('S')
print(arr)
print(arr1)
print(arr1.dtype)

[1 3 2 4 5]
[b'1' b'3' b'2' b'4' b'5']
|S11


In [19]:
arr = np.array([1,3,2,0,5])
arr1 = arr.astype('?')
print(arr)
print(arr1)
print(arr1.dtype)

[1 3 2 0 5]
[ True  True  True False  True]
bool


In [20]:
arr = np.array([[1,2],[3,4]])
for x in arr:
    print(x)

[1 2]
[3 4]


In [22]:
arr = np.array([[1,2],[3,4]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.reshape(2,6)
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.copy()
arr[0] = 40 
print(arr)
print(newarr)

[40  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.copy()
arr[0] = 40 
print(arr)
print(newarr)

In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.view()
newarr[1] = 50
arr[0] = 40 
print(arr)
print(newarr)

[40 50  3  4  5  6  7  8  9 10 11 12]
[40 50  3  4  5  6  7  8  9 10 11 12]


In [30]:
arr = np.array([[[1,2,3],[5,3,5]],[[3,6,4],[5,6,8]]])
print(arr)
print("-----")
print(arr.ndim)
print("-----")
print(arr.shape)

[[[1 2 3]
  [5 3 5]]

 [[3 6 4]
  [5 6 8]]]
-----
3
-----
(2, 2, 3)


In [46]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
newarr = np.concatenate((arr,arr1),axis=1)
print(newarr)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [49]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
newarr = np.concatenate((arr,arr1),axis=0)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
