In [1]:
import numpy as np

In [2]:
arr = np.array([[5,5],[2,3],[7,9]])
for x in np.nditer(arr):
    print(x)

5
5
2
3
7
9


In [20]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
newarr = np.concatenate((arr,arr1),axis=0)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
arr  = np.array([[1,2],[3,4]])
arr1 = np.array([[5,6],[7,8]])
x = np.stack((arr,arr1),axis=1)
print(x)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [4]:
arr  = np.array([[1,2],[3,4]])
arr1 = np.array([[5,6],[7,8]])
x = np.hstack((arr,arr1))
print(x)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
arr  = np.array([[1,2],[3,4]])
arr1 = np.array([[5,6],[7,8]])
x = np.vstack((arr,arr1))
print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
arr = np.array([1,2,3,4,5,6])
newarr =  np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
arr = np.array([1,2,3,4,5,6])
newarr =  np.array_split(arr,5)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [34]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
newarr =  np.hsplit(arr,3)
print(newarr)

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]


In [41]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
newarr =  np.vsplit(arr,2)
print(newarr)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [15]:
arr = np.array([5,4,6,2,9,3])

print(np.sort(arr))

[2 3 4 5 6 9]


In [16]:
#where method is for showing index number
arr = np.array([1,2,3,4,5,6,4,5,4])
newarr =  np.where(arr == 4)
print(newarr)

(array([3, 6, 8], dtype=int64),)


In [17]:
arr = np.array([1,2,3,4,5,6,4,5,4])
newarr =  np.where(arr%2 == 0)
print(newarr)

(array([1, 3, 5, 6, 8], dtype=int64),)


In [19]:
arr =  np.array([1,2,3,4,15,6,7,18])
x = np.where(arr>=15)

print(x)
print(arr[arr>=15])

(array([4, 7], dtype=int64),)
[15 18]


In [44]:
arr = np.array([41,42,43,44])
x = [True,False,True,False]

newarr = arr[x]
print(newarr)

[41 43]


In [50]:
arr1 =  ([10,20,20,20,50,50])
print(np.unique(arr1))
np.unique(arr1)

[10 20 50]


array([10, 20, 50])

In [51]:
x1 =  np.zeros((5,5))
x1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
x1 = np.ones((5,5))
x1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
x = np.full((2,3),70)
x

array([[70, 70, 70],
       [70, 70, 70]])

In [56]:
x = np.full_like(x1,5)
x

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [57]:
x =  np.array([1,20,30,40,5])
np.diff(x)

array([ 19,  10,  10, -35])

In [59]:
np.pad(x,(2,4),mode = 'constant')

array([ 0,  0,  1, 20, 30, 40,  5,  0,  0,  0,  0])

In [60]:
np.pad(x,(2,4),mode = 'constant', constant_values=(10,20))

array([10, 10,  1, 20, 30, 40,  5, 20, 20, 20, 20])

In [61]:
np.pad(x,(2,4))

array([ 0,  0,  1, 20, 30, 40,  5,  0,  0,  0,  0])

In [62]:
x = np.array([1,2,30,4,50])
np.diff(np.pad(x,(1,0)))

array([  1,   1,  28, -26,  46])

In [64]:
x = np.array([1,2,3,4,5])
print(x.mean())
print(x.max())
print(x.min())
print(x.argmax())
print(x.argmin())

3.0
5
1
4
0


In [65]:
y =  np.array([[1,2,3]])
print(y)
x =  np.arange(1,7).reshape(2,3)
print(x)
y = y.transpose()
np.dot(x,y)

[[1 2 3]]
[[1 2 3]
 [4 5 6]]


array([[14],
       [32]])