import numpy liberry and version check

In [1]:
import numpy as np
print(np.__version__)

1.23.5


In [2]:
a1 = [[1.2],[3,4],[5,6]]
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
c = np.array([43])
d = np.array([1,2,3,4])

In [3]:
print(a.ndim)
print("-"*10 , 'Number of array dimensions.')
print(a.shape)
print("-"*10, 'Return the shape of an array.')
print(a.size)
print("-"*10)
print(a.dtype)
print("-"*10)
print(a.itemsize)
print("-"*10)
print(a.nbytes)
print("-"*10)
print(a.data)
print("-"*10)
print(a.strides)
print("-"*10)
print(a.T)

2
---------- Number of array dimensions.
(3, 2)
----------
6
----------
int32
----------
4
----------
24
----------
----------
(8, 4)
----------
[[1 3 5]
 [2 4 6]]


In [10]:
print(b.ndim)
print("-"*10)
print(b.shape)
print("-"*10)
print(b.size)

3
----------
(2, 3, 2)
----------
12


In [11]:
print(c.ndim)
print("-"*10)
print(c.shape)
print("-"*10)
print(c.size)

1
----------
(1,)
----------
1


In [12]:
e = np.array([1,2,3,4],ndmin = 2)
print(e)

[[1 2 3 4]]


In [13]:
arr = np.array([10,20,30,40,50,60])
print(arr[1])
print(arr[2:])
print(arr[:3])
#line itrited 2 by 2
print(arr[0::2])

20
[30 40 50 60]
[10 20 30]
[10 30 50]
